export const ADD_DADOS = 'ADD_DADOS';
export const ADD_TABELA_HOME = 'ADD_TABELA_HOME';
export const ADD_TABELA_ANALISEACAO = 'ADD_TABELA_HOME_ANALISEACAO';
export const ADD_TABELA_MODOANALISTA = 'ADD_TABELA_HOME_MODOANALISTA';
